export const exercises = [
   { name: "Ab Roller", extype: "abs", setcal: 22, imag: "../exerciseimages/ausrollen-kurzhantel-gewichte-800x448.png", info: "The Ab Roller is a core-strengthening exercise that involves a rolling motion to engage the abdominal muscles deeply. It emphasizes stability and control, helping to build strong abs while also involving the lower back and hip flexors for enhanced core endurance and posture." },
   { name: "Arnold Press", extype: "arms", setcal: 30, imag: "../exerciseimages/arnold-press-2.png", info: "The Arnold Press is a variation of the shoulder press that adds rotation to work the deltoids more effectively. Named after Arnold Schwarzenegger, it targets the front, side, and rear delts, creating a well-rounded shoulder workout for muscle growth and upper body stability." },
   { name: "Barbell Squat", extype: "legs", setcal: 50, imag: "../exerciseimages/wadenheben-langhantel-stehend-2.png", info: "Barbell Squats are fundamental to building lower body strength, emphasizing the quadriceps, hamstrings, and glutes. This exercise also engages the core and lower back for stabilization, making it an essential movement for improving leg power, mobility, and overall functional fitness." },
   { name: "Bench Press", extype: "chest", setcal: 40, imag: "../exerciseimages/bankdruecken-flachbank-langhantel.png", info: "The Bench Press is a classic upper-body exercise targeting the pectoral muscles, triceps, and shoulders. It builds chest strength and mass, making it a staple for those looking to improve their upper body power and size while also enhancing stability through its controlled pushing movement." },
   { name: "Bent-Over Row", extype: "back", setcal: 40, imag: "../exerciseimages/rudern-langhantel-800x448.png", info: "Bent-Over Rows are designed to strengthen the back muscles, particularly the latissimus dorsi and rhomboids. By hinging at the hips, this exercise also engages the core, biceps, and lower back, improving posture and upper body stability while boosting muscle endurance in the back." },
   { name: "Bicep Curl", extype: "arms", setcal: 20, imag: "../exerciseimages/bizepscurls-800x448.png", info: "Bicep Curls are an isolation exercise focusing specifically on the biceps, the muscles at the front of the upper arm. Performing curls helps in developing arm strength and muscle tone, making it a fundamental exercise for those aiming to enhance upper body aesthetics and grip strength." },
   { name: "Bicycle Crunch", extype: "abs", setcal: 17, imag: "../exerciseimages/bicycle-exercise-800x448.png", info: "Bicycle Crunches involve a twisting motion that activates both the upper and lower abdominals along with the obliques. This movement not only strengthens the core muscles but also enhances rotational stability, making it effective for improving flexibility and overall abdominal definition." },
   { name: "Cable Chest Fly", extype: "chest", setcal: 38, imag: "../exerciseimages/fliegende-kabelzug.png", info: "Cable Chest Flys are performed using a cable machine, targeting the pectoral muscles through a wide, sweeping motion. This exercise promotes chest development by isolating these muscles, increasing flexibility and the range of motion in the shoulders for a more defined upper body." },
   { name: "Cable Crunch", extype: "abs", setcal: 20, imag: "../exerciseimages/kabelzugcrunches-800x448.png", info: "Cable Crunches add resistance to traditional crunches, intensifying the effort needed to engage the abdominal muscles. This added resistance helps in building a stronger, more defined core while also improving stability and endurance during other physical activities and workouts." },
   { name: "Cable Row", extype: "back", setcal: 34, imag: "../exerciseimages/rudern-kabelzug-800x448.png", info: "Cable Rows focus on strengthening the back muscles, especially the lats and rhomboids, while also engaging the biceps. By pulling the cable towards your torso, this exercise aids in developing a strong, V-shaped back and enhancing upper body endurance." },
   { name: "Cable Tricep Pushdown", extype: "arms", setcal: 25, imag: "../exerciseimages/cable_Press_down.png", info: "Cable Tricep Pushdowns isolate the triceps, effectively building muscle strength and tone in the upper arms. This movement is crucial for enhancing arm definition and is often incorporated into workouts to balance out arm development alongside bicep exercises." },
   { name: "Calf Raise", extype: "legs", setcal: 22, imag: "../exerciseimages/wadenheben-langhantel-stehend-2.png", info: "Calf Raises target the calf muscles, particularly the gastrocnemius and soleus, helping to improve lower leg strength and stability. This exercise is essential for athletes seeking to boost their power in movements like running, jumping, and other explosive leg activities." },
   { name: "Chest Fly", extype: "chest", setcal: 35, imag: "../exerciseimages/fliegende-kabelzug.png", info: "The Chest Fly focuses on expanding and contracting the chest muscles, engaging the pectorals without involving much shoulder movement. This exercise enhances the chest's shape and tone, making it key for those looking to improve upper body aesthetics." },
   { name: "Chest Press Machine", extype: "chest", setcal: 39, imag: "../exerciseimages/brustpresse-flach-800x448.png", info: "The Chest Press Machine provides support for isolating the chest muscles while reducing strain on the shoulders. It's ideal for those new to strength training or anyone wanting a guided movement to build pectoral strength safely and effectively." },
   { name: "Close-Grip Bench Press", extype: "arms", setcal: 29, imag: "../exerciseimages/bankdruecken-langhantel-flach-enger-griff-800x448.png", info: "The Close-Grip Bench Press primarily targets the triceps, though it also engages the chest and shoulders. This variation of the bench press is excellent for building upper arm strength and muscle definition, with an added emphasis on tricep development." },
   { name: "Concentration Curl", extype: "arms", setcal: 19, imag: "../exerciseimages/bizeps-konzentrationscurls-800x448.png", info: "Concentration Curls isolate the biceps, helping to improve muscle peak and definition in the upper arms. By focusing on a single arm at a time, this exercise allows for greater control and contraction, boosting bicep growth and strength effectively." },
   { name: "Crunch", extype: "abs", setcal: 12, imag: "../exerciseimages/crunches-liegend.png", info: "Crunches focus on strengthening the upper abdominal muscles through a simple, controlled movement. They are a staple core exercise that helps improve abdominal tone and stability, making them effective for developing a strong midsection." },
   { name: "Deadlift", extype: "back", setcal: 55, imag: "../exerciseimages/sumo-kreuzheben-1024x573.png", info: "Deadlifts are a full-body exercise primarily targeting the lower back, glutes, and hamstrings. They are fundamental for building strength and power, improving posture, and enhancing overall athletic performance by engaging multiple muscle groups." },
   { name: "Decline Bench Press", extype: "chest", setcal: 41, imag: "../exerciseimages/negativ-bankdruecken-langhantel-800x448.png", info: "The Decline Bench Press emphasizes the lower part of the pectoral muscles. This variation allows for increased chest activation while also reducing strain on the shoulders, making it effective for overall chest development." },
   { name: "Dumbbell Fly", extype: "chest", setcal: 37, imag: "../exerciseimages/fliegende-schraegbank-800x448.png", info: "Dumbbell Flys involve a wide arc motion that targets the chest muscles. This exercise is excellent for stretching and contracting the pecs, contributing to chest definition and upper body flexibility." },
   { name: "Dumbbell Shrug", extype: "back", setcal: 22, imag: "../exerciseimages/shrugs-schraegbank.png", info: "Dumbbell Shrugs focus on the trapezius muscles, helping to build neck and upper back strength. They are a key exercise for developing the muscles that support shoulder movements and improve posture." },
   { name: "Flutter Kick", extype: "abs", setcal: 13, imag: "../exerciseimages/scherenkicks.png", info: "Flutter Kicks are a core exercise that targets the lower abdominals and hip flexors. This movement helps improve lower body endurance and stability, enhancing core strength and toning the lower stomach area." },
   { name: "Front Raise", extype: "arms", setcal: 17, imag: "../exerciseimages/frontheben-kurzhanteln-800x448.png", info: "Front Raises target the front deltoid muscles, strengthening the shoulders and enhancing upper body endurance. This exercise is crucial for building shoulder stability and muscle definition, improving lifting performance." },
   { name: "Hack Squat", extype: "legs", setcal: 49, imag: "../exerciseimages/hackenschmidt-kniebeugen-geraet.png", info: "Hack Squats are a leg-focused exercise emphasizing the quadriceps, glutes, and hamstrings. They offer a stable movement path that helps build lower body strength, making them ideal for those looking to enhance leg power and muscle size." },
   { name: "Hammer Curl", extype: "arms", setcal: 20, imag: "../exerciseimages/bizeps-hammercurls-800x448.png", info: "Hammer Curls are a bicep exercise that also engages the brachialis and forearm muscles. This movement increases overall arm strength and endurance, contributing to balanced upper body muscle development." },
   { name: "Hyperextension", extype: "back", setcal: 28, imag: "../exerciseimages/hyperextension-flachbank.png", info: "Hyperextensions target the lower back, glutes, and hamstrings. They are effective for strengthening the posterior chain and improving spinal stability, which helps prevent lower back injuries and enhances overall posture." },
   { name: "Incline Bench Press", extype: "chest", setcal: 42, imag: "../exerciseimages/schraegbankdruecken-langhantel.png", info: "The Incline Bench Press focuses on the upper part of the chest muscles, emphasizing the front deltoids. It is crucial for developing upper body strength and achieving a balanced, defined chest." },
   { name: "Incline Dumbbell Curl", extype: "arms", setcal: 18, imag: "../exerciseimages/bizepscurls-schraegbank-langhantel-800x448.png", info: "Incline Dumbbell Curls stretch the biceps fully, promoting better muscle contraction and growth. This exercise is effective in building peak bicep strength and size while enhancing arm flexibility." },
   { name: "Lateral Raise", extype: "arms", setcal: 18, imag: "../exerciseimages/seitenheben-kurzhanteln-800x448.png", info: "Lateral Raises isolate the side deltoids, improving shoulder width and upper body aesthetics. They play a significant role in developing shoulder strength and enhancing muscle definition for a well-rounded appearance." },
   { name: "Lat Pulldown", extype: "back", setcal: 33, imag: "../exerciseimages/latzug-1024x573.png", info: "Lat Pulldowns are a key exercise for strengthening the latissimus dorsi, helping to create a broader back. They also engage the biceps and shoulders, improving upper body pulling strength and muscle endurance." },
   { name: "Leg Curl", extype: "legs", setcal: 35, imag: "../exerciseimages/beinbeugen-liegend-geraet.png", info: "Leg Curls isolate the hamstrings, building muscle strength and flexibility in the back of the thigh. This exercise is essential for balanced leg development and improved lower body mobility." },
   { name: "Leg Extension", extype: "legs", setcal: 34, imag: "../exerciseimages/beinstrecken-geraet-1.png", info: "Leg Extensions focus on the quadriceps, enhancing strength and muscle tone in the front of the thighs. This exercise is effective for improving knee joint stability and boosting leg power." },
   { name: "Leg Press", extype: "legs", setcal: 50, imag: "../exerciseimages/beinpresse-800x448.png", info: "The Leg Press targets the quadriceps, hamstrings, and glutes, providing a stable and controlled movement path. It's ideal for building leg strength and muscle size while minimizing lower back strain." },
   { name: "Leg Raise", extype: "abs", setcal: 14, imag: "../exerciseimages/seitliches-knieheben-geraet-800x448.png", info: "Leg Raises work the lower abdominal muscles and hip flexors, enhancing core strength and stability. This exercise is great for improving lower body control and developing a toned midsection." },
   { name: "Lunge", extype: "legs", setcal: 42, imag: "../exerciseimages/ausfallschritt-langhantel.png", info: "Lunges are a dynamic lower body exercise that targets the quadriceps, glutes, and hamstrings. They improve leg strength, balance, and flexibility, making them ideal for enhancing overall lower body function and mobility." },
   { name: "Mountain Climber", extype: "abs", setcal: 18, imag: "../exerciseimages/bergsteiger-fitnessband.png", info: "Mountain Climbers engage the core, arms, and legs, providing a full-body workout that boosts cardiovascular endurance. This high-intensity exercise improves agility, strength, and stability, making it effective for fat-burning routines." },
   { name: "Overhead Shoulder Press", extype: "arms", setcal: 28, imag: "../exerciseimages/schulterdruecken-langhantel-800x448.png", info: "The Overhead Shoulder Press strengthens the shoulders, upper back, and triceps. It is crucial for enhancing upper body stability, muscle endurance, and overall arm strength in a controlled vertical motion." },
   { name: "Overhead Tricep Extension", extype: "arms", setcal: 24, imag: "../exerciseimages/trizepsdruecken-langhantel-800x448.png", info: "Overhead Tricep Extensions specifically target the triceps, improving muscle tone and strength in the back of the arms. This exercise helps with arm stability and overall upper body functionality." },
   { name: "Pec Deck", extype: "chest", setcal: 37, imag: "../exerciseimages/butterflys-800x448.png", info: "The Pec Deck machine isolates the chest muscles, focusing on building pectoral strength and definition. It allows for a controlled movement that effectively engages the upper body." },
   { name: "Preacher Curl", extype: "arms", setcal: 23, imag: "../exerciseimages/preacher-curls-machine.png", info: "Preacher Curls emphasize the biceps, isolating the muscle for maximum growth and strength development. This exercise enhances arm stability and helps to build a well-defined bicep peak." },
   { name: "Pull-Up", extype: "back", setcal: 30, imag: "../exerciseimages/klimmzuege-800x448.png", info: "Pull-Ups are a compound exercise that targets the back, shoulders, and arms. They are essential for building upper body strength, enhancing grip endurance, and improving muscle coordination." },
   { name: "Push-Up", extype: "chest", setcal: 15, imag: "../exerciseimages/liegestuetze-800x448.png", info: "Push-Ups are a versatile bodyweight exercise that works the chest, shoulders, and triceps. This classic movement enhances upper body strength, muscle endurance, and core stability." },
   { name: "Reverse Crunch", extype: "abs", setcal: 16, imag: "../exerciseimages/reverse-crunches-800x448.png", info: "Reverse Crunches target the lower abdominals, helping to build core strength and stability. This exercise is effective for toning the lower stomach area and improving hip mobility." },
   { name: "Reverse Wrist Curl", extype: "arms", setcal: 11, imag: "../exerciseimages/unterarmcurls-langhantel-2-800x448.png", info: "Reverse Wrist Curls strengthen the forearms and improve grip strength. This exercise is ideal for developing wrist stability and enhancing overall arm endurance." },
   { name: "Romanian Deadlift", extype: "legs", setcal: 52, imag: "../exerciseimages/kreuzheben-gestreckte-beine-kurzhantel.png", info: "Romanian Deadlifts target the hamstrings, glutes, and lower back. They are essential for improving posterior chain strength, flexibility, and athletic performance." },
   { name: "Russian Twist", extype: "abs", setcal: 14, imag: "../exerciseimages/bauchtwist-sitzend-gewicht.png", info: "Russian Twists engage the oblique muscles, enhancing core stability and rotational strength. This exercise is great for improving waist definition and overall core endurance." },
   { name: "Seated Row", extype: "back", setcal: 36, imag: "../exerciseimages/rudern-geraet.png", info: "Seated Rows focus on the middle back and lat muscles, enhancing upper body pulling strength. This exercise improves posture and develops a stronger, more defined back." },
   { name: "Shoulder Press", extype: "arms", setcal: 30, imag: "../exerciseimages/schulterdruecken-kurzhanteln-800x448.png", info: "The Shoulder Press strengthens the deltoids, triceps, and upper chest. It is a key exercise for building upper body strength and improving arm endurance and stability." },
   { name: "Sit-Up", extype: "abs", setcal: 15, imag: "../exerciseimages/situps-800x448.png", info: "Sit-Ups primarily target the abdominals, helping to build core strength and endurance. This classic exercise is excellent for toning the midsection and improving overall abdominal stability." },
   { name: "Skull Crusher", extype: "arms", setcal: 26, imag: "../exerciseimages/stirndruecken-langhantel-800x448.png", info: "Skull Crushers focus on the triceps, helping to increase muscle strength and size. This exercise is effective for building the back of the arms and improving overall upper body power." },
   { name: "Squat", extype: "legs", setcal: 45, imag: "../exerciseimages/kniebeugen-kurzhanteln-800x448.png", info: "Squats are a fundamental lower body exercise that targets the quads, glutes, and hamstrings. They enhance leg strength, muscle growth, and stability, making them essential for overall fitness." },
   { name: "Stiff-Leg Deadlift", extype: "legs", setcal: 48, imag: "../exerciseimages/kreuzheben-gestreckte-beine.png", info: "Stiff-Leg Deadlifts primarily engage the hamstrings and lower back. This movement improves flexibility, strength, and stability in the posterior chain, enhancing athletic performance." },
   { name: "Step-Up", extype: "legs", setcal: 40, imag: "../exerciseimages/aufsteiger-langhantel-flachbank-800x448.png", info: "Step-Ups focus on the quads, glutes, and hamstrings, enhancing lower body strength and coordination. They are great for improving balance and developing functional leg power." },
   { name: "T-Bar Row", extype: "back", setcal: 39, imag: "../exerciseimages/rudern-tstange-800x448.png", info: "T-Bar Rows engage the middle back and lats, improving pulling strength and upper body muscle definition. This exercise is crucial for building a stronger, thicker back." },
   { name: "Tricep Dip", extype: "arms", setcal: 25, imag: "../exerciseimages/dips.png", info: "Tricep Dips target the triceps, shoulders, and chest. This bodyweight exercise helps to build upper body strength, tone the arms, and enhance muscle endurance." },
   { name: "Wrist Curl", extype: "arms", setcal: 12, imag: "../exerciseimages/unterarmcurls-kurzhantel-einarmig.png", info: "Wrist Curls strengthen the forearms and improve grip power. They are effective for enhancing wrist stability and overall arm strength, which benefits various upper body exercises." }
];


export const cardioExercises = [
   { name: "Aerobic Dance", mincal: 9, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Badminton", mincal: 7, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Basketball (Playing)", mincal: 11, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Battle Ropes", mincal: 12, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Boxing", mincal: 12, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Burpees", mincal: 14, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Circuit Training", mincal: 14, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Cycling (High Intensity)", mincal: 10, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Cycling (Low Intensity)", mincal: 6, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Dancing", mincal: 8, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Elliptical (High Intensity)", mincal: 11, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Elliptical Trainer", mincal: 7, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "High Knees", mincal: 12, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Hiking", mincal: 7, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Jogging", mincal: 8, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Jump Rope", mincal: 13, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Jumping Jacks", mincal: 10, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Kick Scooter", mincal: 7, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Kickboxing", mincal: 13, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Martial Arts", mincal: 12, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Mountain Climbers", mincal: 11, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Pilates", mincal: 4, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Power Walking", mincal: 6, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Rollerblading", mincal: 10, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Rowing (Competitive)", mincal: 13, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Rowing (Fast)", mincal: 10, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Rowing (Moderate)", mincal: 9, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Rowing (Slow)", mincal: 6, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Rowing Machine", mincal: 8, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Running", mincal: 12, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Skating", mincal: 9, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Skipping", mincal: 10, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Soccer (Playing)", mincal: 12, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Sprinting", mincal: 16, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Stair Climbing", mincal: 10, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Step Aerobics", mincal: 8, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Swimming (Backstroke)", mincal: 9, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Swimming (Breaststroke)", mincal: 8, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Swimming (Freestyle)", mincal: 11, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Tai Chi", mincal: 3, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Tennis", mincal: 9, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Treadmill Running", mincal: 12, extype: "fast-paced", imag: "../exerciseimages/" },
   { name: "Treadmill Walking", mincal: 5, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Walking (Brisk)", mincal: 5, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Walking (Casual)", mincal: 4, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Yoga", mincal: 3, extype: "slow-paced", imag: "../exerciseimages/" },
   { name: "Zumba", mincal: 10, extype: "fast-paced", imag: "../exerciseimages/" }
];

export const flexibilityExercises = [
   { name: "Child's Pose", mincal: 2, parts: "Back, Hips", imag: "../exerciseimages/" },
   { name: "Cat-Cow Stretch", mincal: 3, parts: "Spine, Neck", imag: "../exerciseimages/" },
   { name: "Standing Forward Bend", mincal: 3, parts: "Hamstrings, Lower Back", imag: "../exerciseimages/" },
   { name: "Butterfly Stretch", mincal: 2, parts: "Inner Thighs, Hips", imag: "../exerciseimages/" },
   { name: "Seated Hamstring Stretch", mincal: 3, parts: "Hamstrings, Lower Back", imag: "../exerciseimages/" },
   { name: "Quad Stretch", mincal: 2, parts: "Quadriceps, Hip Flexors", imag: "../exerciseimages/" },
   { name: "Neck Stretch", mincal: 1, parts: "Neck, Shoulders", imag: "../exerciseimages/" },
   { name: "Side Stretch", mincal: 2, parts: "Obliques, Shoulders", imag: "../exerciseimages/" },
   { name: "Hip Flexor Stretch", mincal: 3, parts: "Hip Flexors, Quadriceps", imag: "../exerciseimages/" },
   { name: "Calf Stretch", mincal: 2, parts: "Calves", imag: "../exerciseimages/" },
   { name: "Triceps Stretch", mincal: 2, parts: "Triceps, Shoulders", imag: "../exerciseimages/" },
   { name: "Chest Opener", mincal: 2, parts: "Chest, Shoulders", imag: "../exerciseimages/" },
   { name: "Cobra Stretch", mincal: 3, parts: "Lower Back, Abs", imag: "../exerciseimages/" },
   { name: "Lying Knee-to-Chest Stretch", mincal: 2, parts: "Lower Back, Hips", imag: "../exerciseimages/" },
   { name: "Pigeon Pose", mincal: 3, parts: "Hips, Glutes", imag: "../exerciseimages/" },
   { name: "Arm Circles", mincal: 2, parts: "Shoulders, Arms", imag: "../exerciseimages/" },
   { name: "Wrist Stretch", mincal: 1, parts: "Wrists, Forearms", imag: "../exerciseimages/" },
   { name: "Downward Dog", mincal: 3, parts: "Hamstrings, Calves, Shoulders", imag: "../exerciseimages/" },
   { name: "Lunge Stretch", mincal: 3, parts: "Hip Flexors, Quadriceps", imag: "../exerciseimages/" },
   { name: "Side Lunge Stretch", mincal: 2, parts: "Inner Thighs, Hips", imag: "../exerciseimages/" },
   { name: "Spinal Twist", mincal: 2, parts: "Spine, Lower Back", imag: "../exerciseimages/" },
   { name: "Ankle Circles", mincal: 1, parts: "Ankles, Calves", imag: "../exerciseimages/" },
   { name: "Toe Touch Stretch", mincal: 2, parts: "Hamstrings, Lower Back", imag: "../exerciseimages/" },
   { name: "Groin Stretch", mincal: 2, parts: "Inner Thighs, Groin", imag: "../exerciseimages/" },
   { name: "Bridge Pose", mincal: 3, parts: "Glutes, Lower Back", imag: "../exerciseimages/" },
   { name: "Shoulder Stretch", mincal: 2, parts: "Shoulders, Upper Back", imag: "../exerciseimages/" },
   { name: "Standing Quad Stretch", mincal: 2, parts: "Quadriceps, Hip Flexors", imag: "../exerciseimages/" },
   { name: "Leg Swings", mincal: 3, parts: "Hip Flexors, Glutes", imag: "../exerciseimages/" },
   { name: "Hamstring Stretch", mincal: 2, parts: "Hamstrings, Calves", imag: "../exerciseimages/" },
   { name: "Butterfly Pose", mincal: 2, parts: "Inner Thighs, Hips", imag: "../exerciseimages/" },
   { name: "Reverse Shoulder Stretch", mincal: 2, parts: "Shoulders, Chest", imag: "../exerciseimages/" },
   { name: "Eagle Arms Stretch", mincal: 2, parts: "Shoulders, Upper Back", imag: "../exerciseimages/" },
   { name: "Knee Hug Stretch", mincal: 2, parts: "Lower Back, Glutes", imag: "../exerciseimages/" },
   { name: "Hip Stretch", mincal: 3, parts: "Hips, Glutes", imag: "../exerciseimages/" },
   { name: "Side Bend Stretch", mincal: 2, parts: "Obliques, Shoulders", imag: "../exerciseimages/" },
   { name: "Runner's Stretch", mincal: 3, parts: "Hamstrings, Calves", imag: "../exerciseimages/" },
   { name: "Supine Twist", mincal: 2, parts: "Spine, Lower Back", imag: "../exerciseimages/" },
   { name: "Frog Pose", mincal: 3, parts: "Inner Thighs, Hips", imag: "../exerciseimages/" },
   { name: "Seated Side Stretch", mincal: 2, parts: "Obliques, Shoulders", imag: "../exerciseimages/" },
   { name: "Windshield Wipers", mincal: 2, parts: "Lower Back, Hips", imag: "../exerciseimages/" },
   { name: "Hip Circles", mincal: 2, parts: "Hips, Lower Back", imag: "../exerciseimages/" },
   { name: "Standing Calf Stretch", mincal: 2, parts: "Calves, Ankles", imag: "../exerciseimages/" },
   { name: "Happy Baby Pose", mincal: 3, parts: "Hips, Lower Back", imag: "../exerciseimages/" },
   { name: "Figure Four Stretch", mincal: 3, parts: "Glutes, Hips", imag: "../exerciseimages/" },
   { name: "Low Lunge Stretch", mincal: 3, parts: "Hip Flexors, Quadriceps", imag: "../exerciseimages/" },
   { name: "Wall Calf Stretch", mincal: 2, parts: "Calves, Ankles", imag: "../exerciseimages/" },
   { name: "Half Split Stretch", mincal: 3, parts: "Hamstrings, Calves", imag: "../exerciseimages/" },
   { name: "Extended Puppy Pose", mincal: 3, parts: "Back, Shoulders", imag: "../exerciseimages/" },
   { name: "Seated Forward Fold", mincal: 2, parts: "Hamstrings, Lower Back", imag: "../exerciseimages/" },
   { name: "Thread the Needle Pose", mincal: 2, parts: "Hips, Shoulders", imag: "../exerciseimages/" }
 ];